game.ReplicatedStorage.RemoteEvent.GetAllPlayerScoreBadgeEvent:FireServer()
game.ReplicatedStorage.RemoteEvent.GetFriendScoreBadgeEvent:FireServer()
game.ReplicatedStorage.RemoteEvent.GetGameScoreBadgeEvent:FireServer()
